#!/usr/bin/env bash
# VAULT-ONLY hook. Do NOT ship in the generic code-project blueprint.
# Enforces the two never-touch trees from the second-brain CLAUDE.md (section 4):
#   - wiki/  is an AI-written index into raw/ and is NEVER hand-edited.
#   - raw/   holds original, unaltered ingested assets and is NEVER reorganized.
#
# PreToolUse hook for Edit|Write. Exit 2 = block (deny|ask). Exit 0 = allow.
# Fails CLOSED (deny) if jq is missing — this guards data integrity.

set -uo pipefail

emit() {
  # $1 = decision (deny|ask) ; $2 = reason
  local decision="$1"
  local reason="${2//\"/\\\"}"
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"%s","permissionDecisionReason":"%s"}}\n' "$decision" "$reason"
  exit 2
}

if ! command -v jq >/dev/null 2>&1; then
  emit deny "jq is required for the vault-integrity hook but is not installed."
fi

INPUT=$(cat)
FILE_PATH=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null || true)
[ -z "$FILE_PATH" ] && exit 0

# Normalise to forward slashes (Git Bash may hand us either) and lower-case.
PATH_NORM=$(printf '%s' "$FILE_PATH" | tr '\\' '/')
PATH_LC=$(printf '%s' "$PATH_NORM" | tr '[:upper:]' '[:lower:]')

# --- wiki/ : never hand-edited ------------------------------------------------
# Exception: sync skills legitimately (re)generate wiki/sources.md and
# wiki/best-practices/**. Default those two to "ask" (a sync run confirms);
# everything else under wiki/ is a hard "deny".
case "$PATH_LC" in
  wiki/sources.md|*/wiki/sources.md|wiki/best-practices/*|*/wiki/best-practices/*)
    emit ask "wiki/ is AI-written and regenerated by sync skills. Confirm this is a sync-skill run, not a manual hand-edit (CLAUDE.md section 4)." ;;
  wiki/*|*/wiki/*)
    emit deny "wiki/ is an AI-written index into raw/ and is NEVER hand-edited. Regenerate it via a sync skill instead (CLAUDE.md section 4)." ;;
esac

# --- raw/ : original assets, never reorganized -------------------------------
# Writes into raw/ are only legitimate as sync-skill ingest. Warn (ask) so an
# accidental hand-edit is caught, while a real ingest can proceed.
case "$PATH_LC" in
  raw/*|*/raw/*)
    emit ask "raw/ holds original, unaltered assets and is never reorganized. Confirm this is a sync-skill ingest, not a hand-edit (CLAUDE.md section 4)." ;;
esac

exit 0
